mandant_prefix                             = "Customer A"
citrix_application_name                    = "Calc Citrix Terraform 💡 Innovator 🎬 Showcase"
citrix_application_published_name          = "Calc Citrix-Terraform_Showcase"
citrix_application_description             = "Experience the future of application delivery with our innovative demo that combines the power of Citrix and Terraform. These showcase apps demonstrate how you can create and manage Citrix environments efficiently and automatically with Terraform."
citrix_application_command_line_executable = "C:\\Windows\\system32\\calc.exe"
icon_path                                  = "icons/citrix.ico"